FLAGS = -Wall -Wextra -pedantic -Wconversion

all:
	make mod_log
	make mod_log2

mod_log: mod_log.cpp
	 g++ -Wall -Wextra -pedantic -Wconversion mod_log.cpp -o mod_log
	
mod_log2: mod_log_v2.cpp
	g++ $(FLAGS) mod_log_v2.cpp -o mod_log_v2
